ID96B = """
  // ─── ID 96B — HEMORRAGIA + FERRO ORAL + FERRITINA E SAT NORMALIZADAS ────────
  {
    id: 961,
    label: "ANEMIA PERSISTENTE COM HEMORRAGIA E FERRO EM REPOSIÇÃO — ERITROPOESE EM RECUPERAÇÃO",
    color: "yellow",
    conditions: {
      ferritina:   { min: 24,  max: 336  },
      hemoglobina: { min: 10.0,max: 13.4 },
      vcm:         { min: 75,  max: 105  },
      rdw:         { min: 16.0,max: 999  },
      satTransf:   { min: 20,  max: 50   },
      bariatrica:  false,
      vegetariano: false,
      perda:       true,
      alcoolista:  false,
      transfundido: false,
    },
    diagnostico: "ANEMIA MODERADA COM FERRITINA E SATURAÇÃO DA TRANSFERRINA NORMAIS OU NORMALIZADAS, EM CONTEXTO DE HEMORRAGIA E USO DE FERRO ORAL OU INJETÁVEL. ESSE PADRÃO INDICA QUE A REPOSIÇÃO DE FERRO JÁ CORRIGIU AS RESERVAS E O COMPARTIMENTO CIRCULANTE, MAS A ERITROPOESE AINDA NÃO COMPLETOU A RECUPERAÇÃO DA HEMOGLOBINA — SITUAÇÃO ESPERADA NAS PRIMEIRAS SEMANAS APÓS INÍCIO DO TRATAMENTO. A ANISOCITOSE ELEVADA REFLETE A PRODUÇÃO SIMULTÂNEA DE HEMÁCIAS ANTIGAS (MICROCÍTICAS) E NOVAS (JÁ NORMAIS), UM SINAL POSITIVO DE RESPOSTA AO TRATAMENTO. FRASE DATA.",
    recomendacaoAge1: "MANTER A REPOSIÇÃO DE FERRO E AGUARDAR A RESPOSTA ERITROPOÉTICA, QUE COSTUMA SE COMPLETAR EM 4 A 8 SEMANAS. CONTROLAR A CAUSA DA HEMORRAGIA É FUNDAMENTAL. REPETIR HEMOGRAMA EM 4 SEMANAS PARA CONFIRMAR A RECUPERAÇÃO DA HEMOGLOBINA. AVALIAÇÃO COM HEMATOLOGISTA SE NÃO HOUVER MELHORA.",
    recomendacaoAge2: "MANTER A REPOSIÇÃO DE FERRO E AGUARDAR A RESPOSTA ERITROPOÉTICA. NESSA FAIXA ETÁRIA, A RECUPERAÇÃO PODE SER MAIS LENTA. CONTROLAR A CAUSA DA HEMORRAGIA É FUNDAMENTAL. REPETIR HEMOGRAMA EM 4 SEMANAS. AVALIAÇÃO COM HEMATOLOGISTA SE NÃO HOUVER MELHORA OU SE HOUVER NOVA QUEDA DA HEMOGLOBINA.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRÔNICA DE SANGUE EM MUITOS USUÁRIOS. PODE ESTAR CONTRIBUINDO PARA A HEMORRAGIA E DIFICULTANDO A RECUPERAÇÃO DA ANEMIA. CONSIDERE REVER A PRESCRIÇÃO.",
    comentarioB12: "A REPOSIÇÃO DE VITAMINA B12 PODE TER SIDO BENÉFICA. O FÍGADO ARMAZENA O EXCESSO. NA VIGÊNCIA DE HEMORRAGIA, A NECESSIDADE BIOLÓGICA ESTARÁ AUMENTADA.",
    comentarioFerro: "O FERRO ORAL OU INJETÁVEL NORMALIZOU A FERRITINA E A SATURAÇÃO DA TRANSFERRINA — BOA RESPOSTA AO TRATAMENTO. A ANEMIA PERSISTENTE É TRANSITÓRIA: A ERITROPOESE ESTÁ EM FASE DE RECUPERAÇÃO. MANTENHA A REPOSIÇÃO CONFORME PRESCRITO. CUIDADO AO REPOR FERRO PARENTERAL: O EXCESSO É NOCIVO.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","SANGUE NAS FEZES","ANTI-H. PYLORI IgG/IgM","CEA","CREATININA","ENDOSCOPIA DIGESTIVA","COLONOSCOPIA DE ROTINA"],
  },
"""

ANCORA = "  // ─── ID 98 — ALCOOLISTA SAUDÁVEL"

for filepath in [
    'C:/Users/Estacio/Desktop/redfairy/src/engine/maleMatrix.js',
    'C:/Users/Estacio/Desktop/redfairy/src/engine/femaleMatrix.js',
]:
    with open(filepath, encoding='utf-8') as f:
        txt = f.read()

    if 'id: 961,' in txt:
        print(f'SKIP {filepath} — ID 961 já existe')
        continue

    if ANCORA in txt:
        txt = txt.replace(ANCORA, ID96B + ANCORA)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(txt)
        print(f'OK: ID 961 inserido em {filepath}')
    else:
        print(f'ERRO: âncora não encontrada em {filepath}')
