import re

ID97_MALE = """
  // ─── ID 97 — ALCOOLISTA COM MACROCITOSE SEM ANEMIA ──────────────────────────
  {
    id: 97,
    label: "ALCOOLISTA COM MACROCITOSE SEM ANEMIA",
    color: "yellow",
    conditions: {
      ferritina:   { min: 24,  max: 9999 },
      hemoglobina: { min: 13.5,max: 17.5 },
      vcm:         { min: 101, max: 999  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 20,  max: 999  },
      bariatrica:  false,
      vegetariano: false,
      perda:       false,
      alcoolista:  true,
      transfundido: false,
    },
    diagnostico: "MACROCITOSE SEM ANEMIA EM ALCOOLISTA. O ÁLCOOL INTERFERE DIRETAMENTE NA ERITROPOESE E NO METABOLISMO DO FOLATO, PRODUZINDO MACROCITOSE MESMO SEM DÉFICIT NUTRICIONAL SIGNIFICATIVO. A FERRITINA PODE ESTAR ELEVADA POR HEPATOPATIA ALCOÓLICA, NÃO REFLETINDO NECESSARIAMENTE EXCESSO REAL DE FERRO. SATURAÇÃO DA TRANSFERRINA ELEVADA PODE INDICAR SIDEROSE HEPÁTICA. O DIAGNÓSTICO DIFERENCIAL INCLUI DÉFICIT DE VITAMINA B12, DÉFICIT DE FOLATOS, HIPOTIREOIDISMO E HEPATOPATIA. FRASE DATA.",
    recomendacaoAge1: "AVALIAÇÃO COM HEMATOLOGISTA ASSIM QUE POSSÍVEL. A DOSAGEM DE FOLATOS, VITAMINA B12, TSH, GAMA-GT E AST/ALT É INDISPENSÁVEL. SUPLEMENTAÇÃO DE ÁCIDO FÓLICO É RECOMENDÁVEL. O ÁLCOOL DEVE SER SUSPENSO OU REDUZIDO.",
    recomendacaoAge2: "AVALIAÇÃO COM HEMATOLOGISTA ASSIM QUE POSSÍVEL. NESSA FAIXA ETÁRIA O USO CRÔNICO DE ÁLCOOL COM MACROCITOSE IMPÕE MAIOR RISCO DE DANO HEPÁTICO, NEUROLÓGICO E CARDIOVASCULAR. A DOSAGEM DE FOLATOS, VITAMINA B12, TSH, GAMA-GT E AST/ALT É INDISPENSÁVEL. O ÁLCOOL DEVE SER SUSPENSO.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRÔNICA DE SANGUE EM MUITOS USUÁRIOS. EM ALCOOLISTA, O RISCO DE SANGRAMENTO GASTROINTESTINAL ESTÁ AUMENTADO. AVALIAR BENEFÍCIO/RISCO.",
    comentarioB12: "A REPOSIÇÃO DE VITAMINA B12 PODE TER SIDO BENÉFICA. O ALCOOLISTA FREQUENTEMENTE TEM DÉFICIT COMBINADO DE FOLATOS E B12. SE A MACROCITOSE NÃO CORRIGIR COM PREPARAÇÕES ORAIS, USE VITAMINA B12 SUBLINGUAL OU INJETÁVEL. A DOSAGEM NO SANGUE DEVE SER USADA PARA AJUSTES.",
    comentarioFerro: "A FERRITINA ELEVADA EM ALCOOLISTA PODE REFLETIR HEPATOPATIA ALCOÓLICA, NÃO EXCESSO REAL DE FERRO. NÃO REPONHA FERRO SEM INVESTIGAÇÃO. CUIDADO AO REPOR FERRO, ESPECIALMENTE SE PARENTERAL: O EXCESSO É NOCIVO.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","FOLATOS","VITAMINA B12","TSH","LDH","AST/ALT","GAMA-GT","BILIRRUBINAS","HAPTOGLOBINA","ANTI-FATOR INTRÍNSECO","ANTI-CÉLULAS PARIETAIS","PSA","COLONOSCOPIA DE ROTINA"],
  },
"""

ID97_FEMALE = """
  // ─── ID 97 — ALCOOLISTA COM MACROCITOSE SEM ANEMIA ──────────────────────────
  {
    id: 97,
    label: "ALCOOLISTA COM MACROCITOSE SEM ANEMIA",
    color: "yellow",
    conditions: {
      ferritina:   { min: 24,  max: 9999 },
      hemoglobina: { min: 12.0,max: 15.5 },
      vcm:         { min: 101, max: 999  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 20,  max: 999  },
      bariatrica:  false,
      vegetariano: false,
      perda:       false,
      alcoolista:  true,
      transfundido: false,
    },
    diagnostico: "MACROCITOSE SEM ANEMIA EM ALCOOLISTA. O ÁLCOOL INTERFERE DIRETAMENTE NA ERITROPOESE E NO METABOLISMO DO FOLATO, PRODUZINDO MACROCITOSE MESMO SEM DÉFICIT NUTRICIONAL SIGNIFICATIVO. A FERRITINA PODE ESTAR ELEVADA POR HEPATOPATIA ALCOÓLICA, NÃO REFLETINDO NECESSARIAMENTE EXCESSO REAL DE FERRO. SATURAÇÃO DA TRANSFERRINA ELEVADA PODE INDICAR SIDEROSE HEPÁTICA. O DIAGNÓSTICO DIFERENCIAL INCLUI DÉFICIT DE VITAMINA B12, DÉFICIT DE FOLATOS, HIPOTIREOIDISMO E HEPATOPATIA. FRASE DATA.",
    recomendacaoAge1: "AVALIAÇÃO COM HEMATOLOGISTA ASSIM QUE POSSÍVEL. A DOSAGEM DE FOLATOS, VITAMINA B12, TSH, GAMA-GT E AST/ALT É INDISPENSÁVEL. SUPLEMENTAÇÃO DE ÁCIDO FÓLICO É RECOMENDÁVEL. O ÁLCOOL DEVE SER SUSPENSO OU REDUZIDO.",
    recomendacaoAge2: "AVALIAÇÃO COM HEMATOLOGISTA ASSIM QUE POSSÍVEL. NESSA FAIXA ETÁRIA O USO CRÔNICO DE ÁLCOOL COM MACROCITOSE IMPÕE MAIOR RISCO DE DANO HEPÁTICO, NEUROLÓGICO E CARDIOVASCULAR. A DOSAGEM DE FOLATOS, VITAMINA B12, TSH, GAMA-GT E AST/ALT É INDISPENSÁVEL. O ÁLCOOL DEVE SER SUSPENSO.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRÔNICA DE SANGUE EM MUITOS USUÁRIOS. EM ALCOOLISTA, O RISCO DE SANGRAMENTO GASTROINTESTINAL ESTÁ AUMENTADO. AVALIAR BENEFÍCIO/RISCO.",
    comentarioB12: "A REPOSIÇÃO DE VITAMINA B12 PODE TER SIDO BENÉFICA. O ALCOOLISTA FREQUENTEMENTE TEM DÉFICIT COMBINADO DE FOLATOS E B12. SE A MACROCITOSE NÃO CORRIGIR COM PREPARAÇÕES ORAIS, USE VITAMINA B12 SUBLINGUAL OU INJETÁVEL. A DOSAGEM NO SANGUE DEVE SER USADA PARA AJUSTES.",
    comentarioFerro: "A FERRITINA ELEVADA EM ALCOOLISTA PODE REFLETIR HEPATOPATIA ALCOÓLICA, NÃO EXCESSO REAL DE FERRO. NÃO REPONHA FERRO SEM INVESTIGAÇÃO. CUIDADO AO REPOR FERRO, ESPECIALMENTE SE PARENTERAL: O EXCESSO É NOCIVO.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","FOLATOS","VITAMINA B12","TSH","LDH","AST/ALT","GAMA-GT","BILIRRUBINAS","HAPTOGLOBINA","ANTI-FATOR INTRÍNSECO","ANTI-CÉLULAS PARIETAIS","COLONOSCOPIA DE ROTINA"],
  },
"""

# Ancora de inserção — antes do ID 98 em ambas as matrizes
ANCORA = "  // ─── ID 98 — ALCOOLISTA SAUDÁVEL"

for filepath, id97 in [
    ('C:/Users/Estacio/Desktop/redfairy/src/engine/maleMatrix.js',   ID97_MALE),
    ('C:/Users/Estacio/Desktop/redfairy/src/engine/femaleMatrix.js', ID97_FEMALE),
]:
    with open(filepath, encoding='utf-8') as f:
        txt = f.read()

    if 'id: 97,' in txt:
        print(f'SKIP {filepath} — ID 97 já existe')
        continue

    if ANCORA not in txt:
        print(f'ERRO {filepath} — âncora não encontrada')
        continue

    novo = txt.replace(ANCORA, id97 + ANCORA)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(novo)
    print(f'OK {filepath}')
