"""
add_veg_deficit_misto.py

Cria 3 novas entradas pareadas em femaleMatrix.js e maleMatrix.js
para cobrir o espectro clinico do VEGETARIANO COM DEFICIT MISTO
INCIPIENTE de VITAMINA B12 + FERRO (lacuna identificada pelo
Dr. Ramos).

Caso original que gerou a demanda:
  M 50a, vegetariano, Hb 14, Ferr 29, VCM 103, RDW 18, Sat 16
  -> nao casava com nenhuma entrada existente

Novas entradas:
  ID 101 - Deficit misto INCIPIENTE (amarelo)
    - Hb normal / limite, VCM 101-105, Ferr 24-50, Sat 15-30
  ID 102 - Deficit misto LEVE (laranja)
    - Hb limite inferior, VCM 101-105, Ferr 24-50, Sat 10-20
  ID 103 - Deficit misto MODERADO (laranja escuro)
    - Hb anemica, VCM >105, Ferr <24, Sat <15

Diferencas F vs M: ajuste da Hb (limite inferior feminino 12.0,
masculino 13.5, e limite de normalidade distintos).
"""

from pathlib import Path
import sys

# ═════════════════════════════════════════════════════════════════════
# Entradas para FEMININA
# ═════════════════════════════════════════════════════════════════════
entradas_fem = [
    # ID 101 - INCIPIENTE
    '''
  // ─── ID 101 — VEGETARIANA COM DÉFICIT MISTO INCIPIENTE DE B12 E FERRO ──────
  {
    id: 101,
    label: "VEGETARIANA COM DÉFICIT MISTO INCIPIENTE DE B12 E FERRO",
    color: "yellow",
    conditions: {
      ferritina:   { min: 24,  max: 50   },
      hemoglobina: { min: 12.0,max: 15.5 },
      vcm:         { min: 101, max: 105  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 15,  max: 30   },
      bariatrica:  false,
      vegetariano: true,
      perda:       false,
      alcoolista:  false,
      transfundido: false,
    },
    diagnostico: "DÉFICIT MISTO INCIPIENTE DE VITAMINA B12 E FERRO EM VEGETARIANA. A MACROCITOSE DISCRETA (VCM LIMÍTROFE) ASSOCIADA À FERRITINA NO LIMITE INFERIOR E SATURAÇÃO DA TRANSFERRINA REDUZIDA SINALIZA QUE AS RESERVAS DE AMBOS OS NUTRIENTES ESTÃO SE DEPLETANDO SIMULTANEAMENTE, AINDA SEM CONSEQUÊNCIA ANÊMICA. É UM PADRÃO TÍPICO DA DIETA VEGETARIANA SEM SUPLEMENTAÇÃO ADEQUADA DE B12 E SEM CONSUMO SUFICIENTE DE FERRO HEME. A ANISOCITOSE (RDW > 15) REFLETE A HETEROGENEIDADE DE UMA POPULAÇÃO DE HEMÁCIAS EM DOIS PROCESSOS METABÓLICOS DIFERENTES (MICROCITOSE FERROPRIVA COEXISTINDO COM MACROCITOSE POR B12).",
    recomendacaoAge1: "AVALIAÇÃO COM HEMATOLOGISTA. SOLICITAR DOSAGEM SÉRICA DE VITAMINA B12, ÁCIDO FÓLICO, FERRITINA E SATURAÇÃO DA TRANSFERRINA. INTRODUZIR SUPLEMENTAÇÃO DE B12 SUBLINGUAL OU ORAL (1000 mcg/dia) E FERRO ORAL EM DOSES MODERADAS (30-40 mg de ferro elementar em dias alternados, PREFERENCIALMENTE EM JEJUM OU COM VITAMINA C). NÃO FAÇA DOAÇÃO DE SANGUE ATÉ CORREÇÃO DAS RESERVAS. ENTRE 16 E 17 ANOS DE IDADE É PRECISO AUTORIZAÇÃO DOS RESPONSÁVEIS.",
    recomendacaoAge2: "AVALIAÇÃO COM HEMATOLOGISTA. SOLICITAR DOSAGEM SÉRICA DE VITAMINA B12, ÁCIDO FÓLICO, FERRITINA E SATURAÇÃO DA TRANSFERRINA. INTRODUZIR SUPLEMENTAÇÃO DE B12 SUBLINGUAL OU ORAL (1000 mcg/dia) E FERRO ORAL EM DOSES MODERADAS (30-40 mg de ferro elementar em dias alternados). NESSA FAIXA ETÁRIA, REVISAR ADESÃO À DIETA VEGETARIANA, CONSIDERAR ORIENTAÇÃO NUTRICIONAL ESPECIALIZADA E INVESTIGAR USO DE IBP/METFORMINA QUE POSSAM AGRAVAR O DÉFICIT DE B12. NÃO FAÇA DOAÇÃO DE SANGUE.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRÔNICA DE SANGUE E PODE AGRAVAR A SIDEROPENIA EM CURSO. REAVALIAR A NECESSIDADE DO USO.",
    comentarioB12: "A B12 É NECESSÁRIA. SE A DIETA É ESTRITAMENTE VEGETARIANA, A SUPLEMENTAÇÃO DEVE SER CONTÍNUA E MONITORADA POR DOSAGEM SÉRICA ANUAL. PREFERIR VIA SUBLINGUAL OU INJETÁVEL SE HÁ COMPROMETIMENTO DA ABSORÇÃO.",
    comentarioFerro: "O FERRO É NECESSÁRIO. SUPLEMENTAÇÃO ORAL DEVE SER MANTIDA ATÉ NORMALIZAÇÃO DA FERRITINA (> 100 ng/mL) E SATURAÇÃO (> 25%). EVITAR FERRO PARENTERAL SALVO INDICAÇÃO ESPECÍFICA.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","ÁCIDO FÓLICO","TSH","T4 LIVRE","ANTI-FATOR INTRÍNSECO","ANTI CÉLULA-PARIETAL","HOMOCISTEÍNA","ENDOSCOPIA DIGESTIVA","COLONOSCOPIA DE ROTINA","CEA","CA 15.3","CA 125"],
  },
''',
    # ID 102 - LEVE
    '''
  // ─── ID 102 — VEGETARIANA COM DÉFICIT MISTO LEVE DE B12 E FERRO ────────────
  {
    id: 102,
    label: "VEGETARIANA COM DÉFICIT MISTO LEVE DE B12 E FERRO",
    color: "orange",
    conditions: {
      ferritina:   { min: 24,  max: 50   },
      hemoglobina: { min: 11.5,max: 12.9 },
      vcm:         { min: 101, max: 105  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 10,  max: 20   },
      bariatrica:  false,
      vegetariano: true,
      perda:       false,
      alcoolista:  false,
      transfundido: false,
    },
    diagnostico: "DÉFICIT MISTO LEVE DE VITAMINA B12 E FERRO EM VEGETARIANA, JÁ COM REPERCUSSÃO ANÊMICA INICIAL (HB LIMÍTROFE). A MACROCITOSE DISCRETA E A SATURAÇÃO DA TRANSFERRINA BAIXA REFLETEM DEPLEÇÃO SIMULTÂNEA DAS RESERVAS DE B12 E FERRO, SEMELHANTE AO PADRÃO INCIPIENTE MAS JÁ COM IMPACTO PRODUTIVO. O PADRÃO É TÍPICO DE VEGETARIANISMO PROLONGADO SEM SUPLEMENTAÇÃO ADEQUADA E ALTA PERDA CRÔNICA (MESMO SUBCLÍNICA).",
    recomendacaoAge1: "AVALIAÇÃO COM HEMATOLOGISTA ASSIM QUE POSSÍVEL. INICIAR SUPLEMENTAÇÃO DE B12 (1000 mcg/dia SUBLINGUAL OU ORAL) E FERRO ORAL EM DOSE PLENA (60-80 mg de ferro elementar em dias alternados, EM JEJUM). SOLICITAR DOSAGEM SÉRICA DE B12, ÁCIDO FÓLICO, FERRITINA, SATURAÇÃO DA TRANSFERRINA, RETICULÓCITOS, LDH, HAPTOGLOBINA E HOMOCISTEÍNA. INVESTIGAR PERDAS OCULTAS (ENDOSCOPIA E COLONOSCOPIA). NÃO FAÇA DOAÇÃO DE SANGUE.",
    recomendacaoAge2: "AVALIAÇÃO COM HEMATOLOGISTA ASSIM QUE POSSÍVEL. INICIAR SUPLEMENTAÇÃO DE B12 (1000 mcg/dia SUBLINGUAL OU ORAL) E FERRO ORAL EM DOSE PLENA (60-80 mg de ferro elementar em dias alternados). NESSA FAIXA ETÁRIA, INVESTIGAR GASTRITE ATRÓFICA, H. PYLORI E USO DE IBP/METFORMINA. REALIZAR ENDOSCOPIA E COLONOSCOPIA PARA EXCLUIR PERDA CRÔNICA DE SANGUE. NÃO FAÇA DOAÇÃO DE SANGUE.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRÔNICA DE SANGUE E AGRAVA A SIDEROPENIA. REAVALIAR A NECESSIDADE OU PROTEGER COM IBP — MAS O IBP COMPROMETE ABSORÇÃO DE B12.",
    comentarioB12: "A B12 É NECESSÁRIA. SE A DIETA É ESTRITAMENTE VEGETARIANA, A SUPLEMENTAÇÃO DEVE SER CONTÍNUA. SE A MACROCITOSE NÃO CORRIGIR COM PREPARAÇÕES ORAIS, USE VITAMINA B12 SUBLINGUAL OU INJETÁVEL.",
    comentarioFerro: "O FERRO É NECESSÁRIO. SUPLEMENTAÇÃO ORAL DEVE SER MANTIDA ATÉ NORMALIZAÇÃO COMPLETA DAS RESERVAS (FERRITINA > 100 ng/mL E SATURAÇÃO > 25%). CUIDADO COM FERRO PARENTERAL — PREFERIR ORAL SE TOLERADO.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","ÁCIDO FÓLICO","TSH","T4 LIVRE","ANTI-FATOR INTRÍNSECO","ANTI CÉLULA-PARIETAL","HOMOCISTEÍNA","HAPTOGLOBINA","LDH","ENDOSCOPIA DIGESTIVA","COLONOSCOPIA DE ROTINA","SANGUE NAS FEZES","CEA","CA 15.3","CA 125"],
  },
''',
    # ID 103 - MODERADO
    '''
  // ─── ID 103 — VEGETARIANA COM DÉFICIT MISTO MODERADO DE B12 E FERRO ────────
  {
    id: 103,
    label: "VEGETARIANA COM DÉFICIT MISTO MODERADO DE B12 E FERRO",
    color: "orange",
    conditions: {
      ferritina:   { min: 0,   max: 23   },
      hemoglobina: { min: 9.5, max: 11.9 },
      vcm:         { min: 106, max: 999  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 0,   max: 14   },
      bariatrica:  false,
      vegetariano: true,
      perda:       false,
      alcoolista:  false,
      transfundido: false,
    },
    diagnostico: "DÉFICIT MISTO MODERADO DE VITAMINA B12 E FERRO EM VEGETARIANA, COM ANEMIA JÁ INSTALADA. MACROCITOSE CARACTERÍSTICA (VCM > 105) REFLETE DÉFICIT SIGNIFICATIVO DE B12, ENQUANTO A FERRITINA E A SATURAÇÃO BAIXAS INDICAM RESERVAS ESGOTADAS DE FERRO. ESSE PADRÃO REQUER INTERVENÇÃO MAIS AGRESSIVA QUE OS QUADROS INCIPIENTE OU LEVE. EM ALGUNS CASOS, A CORREÇÃO DO FERRO PODE REVELAR UMA ANEMIA MACROCÍTICA AINDA MAIS MARCADA (FENÔMENO DE DESMASCARAMENTO).",
    recomendacaoAge1: "AVALIAÇÃO URGENTE COM HEMATOLOGISTA. INICIAR IMEDIATAMENTE SUPLEMENTAÇÃO DE B12 INJETÁVEL (1000 mcg IM diária por 7 dias, depois semanal por 4 semanas) E FERRO ORAL EM DOSE PLENA (80-100 mg de ferro elementar em dias alternados). SOLICITAR DOSAGEM SÉRICA DE B12, ÁCIDO FÓLICO, FERRITINA, SATURAÇÃO DA TRANSFERRINA, RETICULÓCITOS, LDH, HAPTOGLOBINA, HOMOCISTEÍNA E ÁCIDO METILMALÔNICO. INVESTIGAR PERDAS OCULTAS. NÃO FAÇA DOAÇÃO DE SANGUE.",
    recomendacaoAge2: "AVALIAÇÃO URGENTE COM HEMATOLOGISTA. INICIAR IMEDIATAMENTE SUPLEMENTAÇÃO DE B12 INJETÁVEL (1000 mcg IM diária por 7 dias, depois semanal por 4 semanas) E FERRO ORAL EM DOSE PLENA. NESSA FAIXA ETÁRIA, INVESTIGAR CUIDADOSAMENTE GASTRITE ATRÓFICA, ANEMIA PERNICIOSA, USO DE IBP/METFORMINA E POSSÍVEL SÍNDROME MIELODISPLÁSICA. REALIZAR ENDOSCOPIA E COLONOSCOPIA. NÃO FAÇA DOAÇÃO DE SANGUE.",
    comentarioAspirina: "ASPIRINA AGRAVA A SIDEROPENIA EM CURSO. REAVALIAR USO COM O MÉDICO PRESCRITOR.",
    comentarioB12: "A B12 DEVE SER INJETÁVEL NO INÍCIO DO TRATAMENTO (DOSE DE ATAQUE), DEPOIS MANUTENÇÃO MENSAL OU ORAL DE ALTA DOSE SUBLINGUAL.",
    comentarioFerro: "O FERRO É ESSENCIAL. PREFERIR ORAL SE TOLERADO. SE INTOLERÂNCIA GÁSTRICA OU MÁ ABSORÇÃO, CONSIDERAR FERRO PARENTERAL APÓS AVALIAÇÃO DO HEMATOLOGISTA.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","ÁCIDO FÓLICO","ÁCIDO METILMALÔNICO","TSH","T4 LIVRE","ANTI-FATOR INTRÍNSECO","ANTI CÉLULA-PARIETAL","HOMOCISTEÍNA","HAPTOGLOBINA","LDH","COOMBS DIRETO","ENDOSCOPIA DIGESTIVA","COLONOSCOPIA DE ROTINA","SANGUE NAS FEZES","CEA","CA 15.3","CA 125"],
  },
''',
]

# ═════════════════════════════════════════════════════════════════════
# Entradas para MASCULINA
# ═════════════════════════════════════════════════════════════════════
entradas_mas = [
    # ID 101 - INCIPIENTE
    '''
  // ─── ID 101 — VEGETARIANO COM DÉFICIT MISTO INCIPIENTE DE B12 E FERRO ──────
  {
    id: 101,
    label: "VEGETARIANO COM DÉFICIT MISTO INCIPIENTE DE B12 E FERRO",
    color: "yellow",
    conditions: {
      ferritina:   { min: 24,  max: 50   },
      hemoglobina: { min: 13.5,max: 17.5 },
      vcm:         { min: 101, max: 105  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 15,  max: 30   },
      bariatrica:  false,
      vegetariano: true,
      perda:       false,
      alcoolista:  false,
      transfundido: false,
    },
    diagnostico: "DÉFICIT MISTO INCIPIENTE DE VITAMINA B12 E FERRO EM VEGETARIANO. A MACROCITOSE DISCRETA (VCM LIMÍTROFE) ASSOCIADA À FERRITINA NO LIMITE INFERIOR E SATURAÇÃO DA TRANSFERRINA REDUZIDA SINALIZA QUE AS RESERVAS DE AMBOS OS NUTRIENTES ESTÃO SE DEPLETANDO SIMULTANEAMENTE, AINDA SEM CONSEQUÊNCIA ANÊMICA. É UM PADRÃO TÍPICO DA DIETA VEGETARIANA SEM SUPLEMENTAÇÃO ADEQUADA DE B12 E SEM CONSUMO SUFICIENTE DE FERRO HEME. A ANISOCITOSE (RDW > 15) REFLETE A HETEROGENEIDADE DE UMA POPULAÇÃO DE HEMÁCIAS EM DOIS PROCESSOS METABÓLICOS DIFERENTES (MICROCITOSE FERROPRIVA COEXISTINDO COM MACROCITOSE POR B12).",
    recomendacaoAge1: "AVALIAÇÃO COM HEMATOLOGISTA. SOLICITAR DOSAGEM SÉRICA DE VITAMINA B12, ÁCIDO FÓLICO, FERRITINA E SATURAÇÃO DA TRANSFERRINA. INTRODUZIR SUPLEMENTAÇÃO DE B12 SUBLINGUAL OU ORAL (1000 mcg/dia) E FERRO ORAL EM DOSES MODERADAS (30-40 mg de ferro elementar em dias alternados, PREFERENCIALMENTE EM JEJUM OU COM VITAMINA C). NÃO FAÇA DOAÇÃO DE SANGUE ATÉ CORREÇÃO DAS RESERVAS.",
    recomendacaoAge2: "AVALIAÇÃO COM HEMATOLOGISTA. SOLICITAR DOSAGEM SÉRICA DE VITAMINA B12, ÁCIDO FÓLICO, FERRITINA E SATURAÇÃO DA TRANSFERRINA. INTRODUZIR SUPLEMENTAÇÃO DE B12 SUBLINGUAL OU ORAL (1000 mcg/dia) E FERRO ORAL EM DOSES MODERADAS (30-40 mg de ferro elementar em dias alternados). NESSA FAIXA ETÁRIA, REVISAR ADESÃO À DIETA VEGETARIANA, CONSIDERAR ORIENTAÇÃO NUTRICIONAL ESPECIALIZADA E INVESTIGAR USO DE IBP/METFORMINA QUE POSSAM AGRAVAR O DÉFICIT DE B12. NÃO FAÇA DOAÇÃO DE SANGUE.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRÔNICA DE SANGUE E PODE AGRAVAR A SIDEROPENIA EM CURSO. REAVALIAR A NECESSIDADE DO USO.",
    comentarioB12: "A B12 É NECESSÁRIA. SE A DIETA É ESTRITAMENTE VEGETARIANA, A SUPLEMENTAÇÃO DEVE SER CONTÍNUA E MONITORADA POR DOSAGEM SÉRICA ANUAL. PREFERIR VIA SUBLINGUAL OU INJETÁVEL SE HÁ COMPROMETIMENTO DA ABSORÇÃO.",
    comentarioFerro: "O FERRO É NECESSÁRIO. SUPLEMENTAÇÃO ORAL DEVE SER MANTIDA ATÉ NORMALIZAÇÃO DA FERRITINA (> 100 ng/mL) E SATURAÇÃO (> 25%). EVITAR FERRO PARENTERAL SALVO INDICAÇÃO ESPECÍFICA.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","ÁCIDO FÓLICO","TSH","T4 LIVRE","ANTI-FATOR INTRÍNSECO","ANTI CÉLULA-PARIETAL","HOMOCISTEÍNA","ENDOSCOPIA DIGESTIVA","COLONOSCOPIA DE ROTINA","CEA","PSA"],
  },
''',
    # ID 102 - LEVE
    '''
  // ─── ID 102 — VEGETARIANO COM DÉFICIT MISTO LEVE DE B12 E FERRO ────────────
  {
    id: 102,
    label: "VEGETARIANO COM DÉFICIT MISTO LEVE DE B12 E FERRO",
    color: "orange",
    conditions: {
      ferritina:   { min: 24,  max: 50   },
      hemoglobina: { min: 12.5,max: 13.4 },
      vcm:         { min: 101, max: 105  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 10,  max: 20   },
      bariatrica:  false,
      vegetariano: true,
      perda:       false,
      alcoolista:  false,
      transfundido: false,
    },
    diagnostico: "DÉFICIT MISTO LEVE DE VITAMINA B12 E FERRO EM VEGETARIANO, JÁ COM REPERCUSSÃO ANÊMICA INICIAL (HB LIMÍTROFE). A MACROCITOSE DISCRETA E A SATURAÇÃO DA TRANSFERRINA BAIXA REFLETEM DEPLEÇÃO SIMULTÂNEA DAS RESERVAS DE B12 E FERRO, SEMELHANTE AO PADRÃO INCIPIENTE MAS JÁ COM IMPACTO PRODUTIVO. O PADRÃO É TÍPICO DE VEGETARIANISMO PROLONGADO SEM SUPLEMENTAÇÃO ADEQUADA E ALTA PERDA CRÔNICA (MESMO SUBCLÍNICA).",
    recomendacaoAge1: "AVALIAÇÃO COM HEMATOLOGISTA ASSIM QUE POSSÍVEL. INICIAR SUPLEMENTAÇÃO DE B12 (1000 mcg/dia SUBLINGUAL OU ORAL) E FERRO ORAL EM DOSE PLENA (60-80 mg de ferro elementar em dias alternados, EM JEJUM). SOLICITAR DOSAGEM SÉRICA DE B12, ÁCIDO FÓLICO, FERRITINA, SATURAÇÃO DA TRANSFERRINA, RETICULÓCITOS, LDH, HAPTOGLOBINA E HOMOCISTEÍNA. INVESTIGAR PERDAS OCULTAS (ENDOSCOPIA E COLONOSCOPIA). NÃO FAÇA DOAÇÃO DE SANGUE.",
    recomendacaoAge2: "AVALIAÇÃO COM HEMATOLOGISTA ASSIM QUE POSSÍVEL. INICIAR SUPLEMENTAÇÃO DE B12 (1000 mcg/dia SUBLINGUAL OU ORAL) E FERRO ORAL EM DOSE PLENA (60-80 mg de ferro elementar em dias alternados). NESSA FAIXA ETÁRIA, INVESTIGAR GASTRITE ATRÓFICA, H. PYLORI E USO DE IBP/METFORMINA. REALIZAR ENDOSCOPIA E COLONOSCOPIA PARA EXCLUIR PERDA CRÔNICA DE SANGUE. NÃO FAÇA DOAÇÃO DE SANGUE.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRÔNICA DE SANGUE E AGRAVA A SIDEROPENIA. REAVALIAR A NECESSIDADE OU PROTEGER COM IBP — MAS O IBP COMPROMETE ABSORÇÃO DE B12.",
    comentarioB12: "A B12 É NECESSÁRIA. SE A DIETA É ESTRITAMENTE VEGETARIANA, A SUPLEMENTAÇÃO DEVE SER CONTÍNUA. SE A MACROCITOSE NÃO CORRIGIR COM PREPARAÇÕES ORAIS, USE VITAMINA B12 SUBLINGUAL OU INJETÁVEL.",
    comentarioFerro: "O FERRO É NECESSÁRIO. SUPLEMENTAÇÃO ORAL DEVE SER MANTIDA ATÉ NORMALIZAÇÃO COMPLETA DAS RESERVAS (FERRITINA > 100 ng/mL E SATURAÇÃO > 25%). CUIDADO COM FERRO PARENTERAL — PREFERIR ORAL SE TOLERADO.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","ÁCIDO FÓLICO","TSH","T4 LIVRE","ANTI-FATOR INTRÍNSECO","ANTI CÉLULA-PARIETAL","HOMOCISTEÍNA","HAPTOGLOBINA","LDH","ENDOSCOPIA DIGESTIVA","COLONOSCOPIA DE ROTINA","SANGUE NAS FEZES","CEA","PSA"],
  },
''',
    # ID 103 - MODERADO
    '''
  // ─── ID 103 — VEGETARIANO COM DÉFICIT MISTO MODERADO DE B12 E FERRO ────────
  {
    id: 103,
    label: "VEGETARIANO COM DÉFICIT MISTO MODERADO DE B12 E FERRO",
    color: "orange",
    conditions: {
      ferritina:   { min: 0,   max: 23   },
      hemoglobina: { min: 10.5,max: 12.4 },
      vcm:         { min: 106, max: 999  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 0,   max: 14   },
      bariatrica:  false,
      vegetariano: true,
      perda:       false,
      alcoolista:  false,
      transfundido: false,
    },
    diagnostico: "DÉFICIT MISTO MODERADO DE VITAMINA B12 E FERRO EM VEGETARIANO, COM ANEMIA JÁ INSTALADA. MACROCITOSE CARACTERÍSTICA (VCM > 105) REFLETE DÉFICIT SIGNIFICATIVO DE B12, ENQUANTO A FERRITINA E A SATURAÇÃO BAIXAS INDICAM RESERVAS ESGOTADAS DE FERRO. ESSE PADRÃO REQUER INTERVENÇÃO MAIS AGRESSIVA QUE OS QUADROS INCIPIENTE OU LEVE. EM ALGUNS CASOS, A CORREÇÃO DO FERRO PODE REVELAR UMA ANEMIA MACROCÍTICA AINDA MAIS MARCADA (FENÔMENO DE DESMASCARAMENTO).",
    recomendacaoAge1: "AVALIAÇÃO URGENTE COM HEMATOLOGISTA. INICIAR IMEDIATAMENTE SUPLEMENTAÇÃO DE B12 INJETÁVEL (1000 mcg IM diária por 7 dias, depois semanal por 4 semanas) E FERRO ORAL EM DOSE PLENA (80-100 mg de ferro elementar em dias alternados). SOLICITAR DOSAGEM SÉRICA DE B12, ÁCIDO FÓLICO, FERRITINA, SATURAÇÃO DA TRANSFERRINA, RETICULÓCITOS, LDH, HAPTOGLOBINA, HOMOCISTEÍNA E ÁCIDO METILMALÔNICO. INVESTIGAR PERDAS OCULTAS. NÃO FAÇA DOAÇÃO DE SANGUE.",
    recomendacaoAge2: "AVALIAÇÃO URGENTE COM HEMATOLOGISTA. INICIAR IMEDIATAMENTE SUPLEMENTAÇÃO DE B12 INJETÁVEL (1000 mcg IM diária por 7 dias, depois semanal por 4 semanas) E FERRO ORAL EM DOSE PLENA. NESSA FAIXA ETÁRIA, INVESTIGAR CUIDADOSAMENTE GASTRITE ATRÓFICA, ANEMIA PERNICIOSA, USO DE IBP/METFORMINA E POSSÍVEL SÍNDROME MIELODISPLÁSICA. REALIZAR ENDOSCOPIA E COLONOSCOPIA. NÃO FAÇA DOAÇÃO DE SANGUE.",
    comentarioAspirina: "ASPIRINA AGRAVA A SIDEROPENIA EM CURSO. REAVALIAR USO COM O MÉDICO PRESCRITOR.",
    comentarioB12: "A B12 DEVE SER INJETÁVEL NO INÍCIO DO TRATAMENTO (DOSE DE ATAQUE), DEPOIS MANUTENÇÃO MENSAL OU ORAL DE ALTA DOSE SUBLINGUAL.",
    comentarioFerro: "O FERRO É ESSENCIAL. PREFERIR ORAL SE TOLERADO. SE INTOLERÂNCIA GÁSTRICA OU MÁ ABSORÇÃO, CONSIDERAR FERRO PARENTERAL APÓS AVALIAÇÃO DO HEMATOLOGISTA.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","ÁCIDO FÓLICO","ÁCIDO METILMALÔNICO","TSH","T4 LIVRE","ANTI-FATOR INTRÍNSECO","ANTI CÉLULA-PARIETAL","HOMOCISTEÍNA","HAPTOGLOBINA","LDH","COOMBS DIRETO","ENDOSCOPIA DIGESTIVA","COLONOSCOPIA DE ROTINA","SANGUE NAS FEZES","CEA","PSA"],
  },
''',
]

# ═════════════════════════════════════════════════════════════════════
# Aplicacao
# ═════════════════════════════════════════════════════════════════════
def aplicar(path: Path, entradas: list, sexo: str):
    if not path.exists():
        print(f"ERRO: {path} nao existe.")
        return False

    src = path.read_text(encoding="utf-8")
    adicionados = 0
    ja_existentes = 0

    for entrada in entradas:
        # Extrai o id da entrada
        import re
        id_match = re.search(r'id:\s*(\d+)', entrada)
        if not id_match:
            continue
        id_num = id_match.group(1)

        if f"id: {id_num}" in src:
            ja_existentes += 1
            print(f"  AVISO ({sexo}): ID {id_num} ja existe, pulando.")
            continue

        idx = src.rfind("];")
        if idx < 0:
            print(f"ERRO ({sexo}): fim do array nao encontrado em {path}.")
            return False

        src = src[:idx] + entrada + src[idx:]
        adicionados += 1
        print(f"  OK ({sexo}): ID {id_num} adicionado.")

    path.write_text(src, encoding="utf-8")
    print(f"  Total {sexo}: {adicionados} novas entradas, {ja_existentes} ja existentes.")
    return True

print("=" * 60)
print("FEMININA")
print("=" * 60)
if not aplicar(Path("src/engine/femaleMatrix.js"), entradas_fem, "FEM"):
    sys.exit(1)

print()
print("=" * 60)
print("MASCULINA")
print("=" * 60)
if not aplicar(Path("src/engine/maleMatrix.js"), entradas_mas, "MAS"):
    sys.exit(1)

print()
print("=" * 60)
print("TUDO OK!")
print("=" * 60)
print()
print("Novas entradas pareadas (F + M):")
print("  ID 101 - VEGETARIANO(A) COM DEFICIT MISTO INCIPIENTE  (amarelo)")
print("  ID 102 - VEGETARIANO(A) COM DEFICIT MISTO LEVE        (laranja)")
print("  ID 103 - VEGETARIANO(A) COM DEFICIT MISTO MODERADO    (laranja)")
print()
print("Caso do Dr. Ramos agora coberto:")
print("  M 50a vegetariano, Hb 14, Ferr 29, VCM 103, RDW 18, Sat 16")
print("  -> ID 101 (incipiente) na maleMatrix")
print()
print("Proximo passo:")
print('  git add . && git commit -m "feat: cobertura deficit misto vegetariano (IDs 101-103 F+M)" && git push origin main')
