-- =============================================================================
-- migrate_indicadores.sql  (Fase 1a — fundação do 3º perfil INDICADOR)
-- =============================================================================
-- Cria as tabelas do INDICADOR (qualquer pessoa que indica bariátricos e ganha
-- US$10 quando o indicado PAGA). Aditivo e seguro — não mexe no fluxo do médico.
-- A atribuição/trigger (regra "quem o paciente escolheu pagar") vem em SQL separado.
--
-- COMO USAR: Supabase Dashboard -> SQL Editor -> cole -> Run.
-- =============================================================================

-- 1) Indicadores (auth própria: CPF + senha; recebe via PIX ou USDC).
CREATE TABLE IF NOT EXISTS public.indicadores (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo              text UNIQUE NOT NULL,            -- vai no link ?ref=<codigo>
  cpf                 text UNIQUE NOT NULL,
  nome                text,
  celular             text,
  email               text,
  tipo                text,                            -- enfermeiro | fisio | leigo | ...
  pix_chave           text,
  usdc_wallet         text,                            -- carteira USDC (opcional)
  senha_klipbit       text,                            -- hash da senha (igual paciente)
  session_token_hash  text,
  session_token_exp   timestamp with time zone,
  ativo               boolean NOT NULL DEFAULT true,
  created_at          timestamp with time zone NOT NULL DEFAULT now()
);

-- 2) Ledger de créditos do indicador (espelha creditos_medico).
CREATE TABLE IF NOT EXISTS public.creditos_indicador (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indicador_codigo text NOT NULL,
  cpf_paciente    text UNIQUE NOT NULL,               -- 1 crédito por paciente
  assinatura_id   uuid,
  valor           integer NOT NULL DEFAULT 1,          -- nº de créditos (US$ vem da config)
  elegivel        boolean NOT NULL DEFAULT true,       -- indicador é elegível na hora
  pago            boolean NOT NULL DEFAULT false,
  data_pagamento  timestamp with time zone,
  created_at      timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_creditos_indicador_codigo ON public.creditos_indicador (indicador_codigo);
CREATE INDEX IF NOT EXISTS idx_indicadores_cpf ON public.indicadores (cpf);

-- 3) RLS LIGADO e SEM policies: contêm senha (hash), PIX/USDC e crédito financeiro.
--    Todo acesso será via RPCs SECURITY DEFINER (cadastro/login/painel/trigger),
--    como já é o padrão de creditos_medico. A chave anônima não lê nada destas tabelas.
ALTER TABLE public.indicadores        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creditos_indicador ENABLE ROW LEVEL SECURITY;
