-- =============================================================================
-- migrate_indicador_atribuicao.sql  (Fase 1c — atribuição + pré-cadastro + trigger)
-- =============================================================================
-- Regra unificada "escolhido no pagamento": vence o referenciador MAIS RECENTE
-- (maior created_at) entre QR/triagem (medico_crm) e o pré-cadastro do indicador.
-- O trigger roteia: código de indicador → creditos_indicador; senão → médico
-- (default, preserva o caso de CRM que indicou sem ter conta).
--
-- COMO USAR: Supabase Dashboard -> SQL Editor -> cole -> Run.
-- =============================================================================

-- 1) Pré-cadastros do indicador (reserva por CPF; pode haver vários — vence o + recente)
CREATE TABLE IF NOT EXISTS public.indicacoes_precadastro (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpf_paciente     text NOT NULL,
  indicador_codigo text NOT NULL,
  created_at       timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_precadastro_cpf    ON public.indicacoes_precadastro (cpf_paciente);
CREATE INDEX IF NOT EXISTS idx_precadastro_codigo ON public.indicacoes_precadastro (indicador_codigo);
ALTER TABLE public.indicacoes_precadastro ENABLE ROW LEVEL SECURITY;  -- acesso só via RPC

-- 2) Trigger unificado (substitui a versão "primeiro" por "mais recente / escolhido").
CREATE OR REPLACE FUNCTION public.fn_credita_medico()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_cpf  text;
  v_orig text;
  v_rows int;
  v_nome text;
  v_pix  text;
  v_usd  numeric;
  v_cot  numeric;
  v_cpfd text;
  v_msg  text;
  v_elegivel boolean;
BEGIN
  IF NEW.status <> 'ativa' THEN
    RETURN NEW;
  END IF;

  SELECT cpf INTO v_cpf FROM public.profiles WHERE id = NEW.user_id;
  IF v_cpf IS NULL THEN
    RETURN NEW;
  END IF;

  -- "Escolhido no pagamento": referenciador MAIS RECENTE (QR/triagem ∪ pré-cadastro).
  SELECT ref_codigo INTO v_orig FROM (
    SELECT medico_crm AS ref_codigo, created_at FROM public.triagens
      WHERE cpf = v_cpf AND medico_crm IS NOT NULL AND btrim(medico_crm) <> ''
    UNION ALL
    SELECT medico_crm, created_at FROM public.avaliacoes
      WHERE cpf = v_cpf AND medico_crm IS NOT NULL AND btrim(medico_crm) <> ''
    UNION ALL
    SELECT indicador_codigo, created_at FROM public.indicacoes_precadastro
      WHERE cpf_paciente = v_cpf
  ) s
  ORDER BY created_at DESC
  LIMIT 1;

  IF v_orig IS NULL OR btrim(v_orig) = '' THEN
    RETURN NEW;
  END IF;

  v_usd := COALESCE((SELECT NULLIF(valor,'')::numeric FROM public.config WHERE chave = 'comissao_usd_por_conversao'), 10);
  v_cot := COALESCE((SELECT NULLIF(valor,'')::numeric FROM public.config WHERE chave = 'cotacao_dolar'), 0);
  v_cpfd := regexp_replace(coalesce(v_cpf,''), '\D', '', 'g');
  v_cpfd := CASE WHEN length(v_cpfd) = 11
                 THEN '***.' || substr(v_cpfd,4,3) || '.' || substr(v_cpfd,7,3) || '-**'
                 ELSE coalesce(v_cpf,'-') END;

  -- ── INDICADOR (código próprio) ──────────────────────────────────────────────
  IF EXISTS (SELECT 1 FROM public.indicadores WHERE codigo = v_orig) THEN
    INSERT INTO public.creditos_indicador (indicador_codigo, cpf_paciente, assinatura_id, elegivel)
    VALUES (v_orig, v_cpf, NEW.id, true)
    ON CONFLICT (cpf_paciente) DO NOTHING;

    GET DIAGNOSTICS v_rows = ROW_COUNT;
    IF v_rows = 0 THEN RETURN NEW; END IF;  -- já creditado: não notifica de novo

    SELECT nome, COALESCE(NULLIF(pix_chave,''), usdc_wallet)
      INTO v_nome, v_pix FROM public.indicadores WHERE codigo = v_orig;
    v_msg := '💸 Nova indicação paga (INDICADOR)!' || E'\n' ||
             'Indicador: ' || COALESCE(NULLIF(v_nome,''), v_orig) || ' (' || v_orig || ')' || E'\n' ||
             'Paciente ' || v_cpfd || ' cadastrou e pagou.' || E'\n' ||
             'Pagar: US$ ' || to_char(v_usd, 'FM999990.00') ||
             CASE WHEN v_cot > 0 THEN ' ≈ R$ ' || to_char(v_usd * v_cot, 'FM999990.00') ELSE '' END || E'\n' ||
             'Receber em: ' || COALESCE(NULLIF(v_pix,''), '(sem PIX/USDC cadastrado)');
    PERFORM public.tg_enviar(v_msg);
    RETURN NEW;
  END IF;

  -- ── MÉDICO (default — preserva CRM que indicou sem ter conta) ────────────────
  UPDATE public.profiles SET medico_origem = v_orig WHERE id = NEW.user_id;
  v_elegivel := public.medico_tem_avaliacao_completa(v_orig);

  INSERT INTO public.creditos_medico (medico_crm, cpf_paciente, assinatura_id, elegivel)
  VALUES (v_orig, v_cpf, NEW.id, v_elegivel)
  ON CONFLICT (cpf_paciente) DO NOTHING;

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows = 0 THEN RETURN NEW; END IF;
  IF NOT v_elegivel THEN RETURN NEW; END IF;

  SELECT nome, pix_chave INTO v_nome, v_pix FROM public.medicos WHERE crm = v_orig;
  v_msg := '💰 Nova comissão 4DOC!' || E'\n' ||
           'Médico: ' || COALESCE(NULLIF(v_nome,''), v_orig) || ' (CRM ' || v_orig || ')' || E'\n' ||
           'Paciente ' || v_cpfd || ' cadastrou e pagou.' || E'\n' ||
           'Pagar: US$ ' || to_char(v_usd, 'FM999990.00') ||
           CASE WHEN v_cot > 0 THEN ' ≈ R$ ' || to_char(v_usd * v_cot, 'FM999990.00') ELSE '' END || E'\n' ||
           'PIX: ' || COALESCE(NULLIF(v_pix,''), '(médico sem chave PIX cadastrada)');
  PERFORM public.tg_enviar(v_msg);
  RETURN NEW;
END;
$function$;

-- 3) precadastrar_indicacao → reserva um CPF para o indicador.
--    Se o paciente já pagou (tem crédito em qualquer ledger) → "JÁ FAZ PARTE DO PROJETO".
CREATE OR REPLACE FUNCTION public.precadastrar_indicacao(p_codigo text, p_cpf text)
  RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public', 'extensions'
AS $$
DECLARE
  v_cpf text := translate(coalesce(p_cpf, ''), '.- /()', '');
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.indicadores WHERE codigo = p_codigo AND ativo) THEN
    RETURN jsonb_build_object('ok', false, 'erro', 'Indicador inválido');
  END IF;
  IF length(v_cpf) <> 11 THEN
    RETURN jsonb_build_object('ok', false, 'erro', 'CPF inválido');
  END IF;
  IF EXISTS (SELECT 1 FROM public.creditos_indicador WHERE cpf_paciente = v_cpf)
     OR EXISTS (SELECT 1 FROM public.creditos_medico WHERE cpf_paciente = v_cpf) THEN
    RETURN jsonb_build_object('ok', false, 'ja_no_projeto', true, 'erro', 'ESSE PACIENTE JÁ FAZ PARTE DO PROJETO');
  END IF;
  INSERT INTO public.indicacoes_precadastro (cpf_paciente, indicador_codigo)
  VALUES (v_cpf, p_codigo);
  RETURN jsonb_build_object('ok', true);
END;
$$;

-- 4) listar_creditos_indicador → dados do painel (CPFs mascarados).
--    NOTA DE SEGURANÇA: aceita só o código (que é público no link). Para MVP os dados
--    são mascarados (3 últimos dígitos) + contagens. Endurecer depois com token de sessão.
CREATE OR REPLACE FUNCTION public.listar_creditos_indicador(p_codigo text)
  RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public', 'extensions'
AS $$
DECLARE
  v_usd  numeric;
  v_pre  jsonb;
  v_cred jsonb;
BEGIN
  v_usd := COALESCE((SELECT NULLIF(valor,'')::numeric FROM public.config WHERE chave = 'comissao_usd_por_conversao'), 10);

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'cpf',  '…' || right(regexp_replace(cpf_paciente, '\D', '', 'g'), 3),
           'data', created_at) ORDER BY created_at DESC), '[]'::jsonb)
    INTO v_pre FROM public.indicacoes_precadastro WHERE indicador_codigo = p_codigo;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'cpf',  '…' || right(regexp_replace(cpf_paciente, '\D', '', 'g'), 3),
           'pago', pago,
           'data', created_at) ORDER BY created_at DESC), '[]'::jsonb)
    INTO v_cred FROM public.creditos_indicador WHERE indicador_codigo = p_codigo;

  RETURN jsonb_build_object('ok', true, 'comissao_usd', v_usd, 'precadastros', v_pre, 'creditos', v_cred);
END;
$$;

GRANT EXECUTE ON FUNCTION public.precadastrar_indicacao(text, text)  TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.listar_creditos_indicador(text)     TO anon, authenticated;
