# RedFairy — Adicionar IDs de Alcoolismo (20, 21, 22, 23) nas matrizes
# Execute em: C:\Users\Estacio\Desktop\redfairy\src\engine
# powershell -ExecutionPolicy Bypass -File add_alcoolismo.ps1

$dir = Split-Path -Parent $MyInvocation.MyCommand.Path
$fem = Join-Path $dir "femaleMatrix.js"
$mal = Join-Path $dir "maleMatrix.js"

$novasEntradas = @'

  // ─── ID 20 — ALCOOLISMO: MACROCITOSE SEM ANEMIA ─────────────────────────────
  {
    id: 20,
    label: "ALCOOLISMO — MACROCITOSE SEM ANEMIA",
    color: "yellow",
    conditions: {
      ferritina:   { min: 24,  max: 400  },
      hemoglobina: { min: 13.5,max: 17.5 },
      vcm:         { min: 101, max: 115  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 20,  max: 80   },
      bariatrica:  false,
      vegetariano: false,
      perda:       false,
      alcoolista:  true,
      transfundido: false,
    },
    diagnostico: "A PRESENÇA DE CÉLULAS VERMELHAS MAIORES PODE OCORRER ANTES DO ESTABELECIMENTO DE ANEMIA, COMO SE VÊ NESSA AVALIAÇÃO.\nO ABUSO DE ÁLCOOL É CAUSA FREQUENTE DESSA CONDIÇÃO, MAS MEDICAMENTOS COMO METFORMINA OU INIBIDORES DA BOMBA DE PRÓTONS (PANTOPRAZOL, OMEPRAZOL), HIDROXIUREIA, METOTREXATO, OU UMA GASTRITE AUTOIMUNE PODEM CONTRIBUIR PARA ESSA ANOMALIA, OU SER FATOR DETERMINANTE.\nA CARÊNCIA DE FOLATOS É COMUM NO ALCOOLISMO, AGRAVA A CONDIÇÃO E CONTRIBUI PARA O DESENVOLVIMENTO DE ANEMIA.\nFRASE DATA",
    recomendacaoAge1: "AVALIAÇÃO COM HEMATOLOGISTA.\nINICIE ÁCIDO FÓLICO, 5 mg VIA ORAL POR DIA.\nSE VOCÊ DOOU SANGUE NOS ÚLTIMOS MESES, PODE TER SIDO PREJUDICIAL.\nVOCÊ PRECISARÁ SER AVALIADO POR MÉDICO ANTES DE DOAR SANGUE.",
    recomendacaoAge2: "AVALIAÇÃO COM HEMATOLOGISTA.\nESSA CONDIÇÃO, NESSA FAIXA ETÁRIA IMPÕE GARANTIR A SUPLEMENTAÇÃO DE ÁCIDO FÓLICO, VITAMINA B12, PROTEÍNAS, SAIS E OUTRAS VITAMINAS.\nSE VOCÊ DOOU SANGUE NOS ÚLTIMOS MESES, PODE TER SIDO PREJUDICIAL.\nVOCÊ PRECISARÁ SER AVALIADO POR MÉDICO ANTES DE DOAR SANGUE.",
    comentarioAspirina: "ASPIRINA IMPÕE PEQUENA PERDA CRÔNICA DE SANGUE À MAIORIA DOS USUÁRIOS, MAS AQUI NÃO SE OBSERVA IMPACTO NEGATIVO.",
    comentarioB12: "A VITAMINA B12 NÃO ERA NECESSÁRIA, MAS DEVE TER SIDO BENÉFICA. MAS FOI INSUFICIENTE, OU ALGO IMPEDIU A SUA ABSORÇÃO, OU A MACROCITOSE NÃO É POR FALTA DELA. SERIA INTERESSANTE O USO DE VITAMINA B12 SUBLINGUAL OU INJETÁVEL. A DOSAGEM NO SANGUE DESSA VITAMINA E DO ÁCIDO FÓLICO É IMPORTANTE NESSE CONTEXTO.",
    comentarioFerro: "O FERRO FOI PROVAVELMENTE DESNECESSÁRIO, MAS SE HAVIA DÉFICIT, FOI CORRIGIDO. MAS SE A FERRITINA ESTÁ ALTA, TAMBÉM PODE TER SIDO NOCIVO. CUIDADO AO REPOR FERRO, ESPECIALMENTE SE PARENTERAL: O EXCESSO É TÓXICO.",
    proximosExames: ["HEMOGRAMA","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","ÁCIDO FÓLICO","AST/ALT","LDH","TSH","GAMA-GT","ELETROFORESE DE PROTEÍNAS","HAPTOGLOBINA","ANTI-H. PYLORI IgG/IgM","PSA","COLONOSCOPIA DE ROTINA"],
  },
  // ─── ID 21 — ALCOOLISMO GRAVE: ANEMIA LEVE A MODERADA ───────────────────────
  {
    id: 21,
    label: "ALCOOLISMO GRAVE — ANEMIA MACROCÍTICA MODERADA",
    color: "orange",
    conditions: {
      ferritina:   { min: 24,  max: 600  },
      hemoglobina: { min: 12.5,max: 13.4 },
      vcm:         { min: 101, max: 120  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 20,  max: 80   },
      bariatrica:  false,
      vegetariano: false,
      perda:       false,
      alcoolista:  true,
      transfundido: false,
    },
    diagnostico: "A PRESENÇA DE CÉLULAS VERMELHAS MAIORES COM ANEMIA, NO CONTEXTO DESSA AVALIAÇÃO, SINALIZA CONDIÇÃO MAIS GRAVE, MAIOR IMPACTO TÓXICO E/OU CARENCIAL.\nO ABUSO DE ÁLCOOL É CAUSA FREQUENTE DESSA CONDIÇÃO, MUITAS VEZES AGRAVADO POR MEDICAMENTOS COMO METFORMINA OU INIBIDORES DA BOMBA DE PRÓTONS (PANTOPRAZOL, OMEPRAZOL). OUTROS MEDICAMENTOS COMO HIDROXIUREIA, METOTREXATO, OU UMA GASTRITE AUTOIMUNE PODEM CONTRIBUIR PARA ESSA ANOMALIA, OU SER FATOR DETERMINANTE.\nA CARÊNCIA DE FOLATOS É COMUM NO ALCOOLISMO, AGRAVA A CONDIÇÃO E CONTRIBUI PARA O DESENVOLVIMENTO DE ANEMIA.\nFRASE DATA",
    recomendacaoAge1: "AVALIAÇÃO COM HEMATOLOGISTA ASSIM QUE POSSÍVEL.\nSE VOCÊ DOOU SANGUE NOS ÚLTIMOS MESES, PODE TER SIDO PREJUDICIAL.\nVOCÊ PRECISARÁ SER AVALIADO POR MÉDICO ANTES DE DOAR SANGUE.\nSOMENTE SE RECUPERADO VOCÊ PODERÁ DOAR SANGUE.",
    recomendacaoAge2: "AVALIAÇÃO COM HEMATOLOGISTA ASSIM QUE POSSÍVEL.\nO DESENVOLVIMENTO DE ANEMIA NESSA CONDIÇÃO E FAIXA ETÁRIA SUGEREM DOENÇA MAIS IMPORTANTE.\nÉ IMPERATIVO SUPLEMENTAR ÁCIDO FÓLICO, VITAMINA B12, PROTEÍNAS, SAIS E OUTRAS VITAMINAS.\nSE VOCÊ DOOU SANGUE NOS ÚLTIMOS MESES, PODE TER SIDO PREJUDICIAL.\nVOCÊ PRECISARÁ SER AVALIADO POR MÉDICO ANTES DE DOAR SANGUE.\nSOMENTE SE RECUPERADO VOCÊ PODERÁ DOAR SANGUE.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRÔNICA DE SANGUE EM MUITOS USUÁRIOS. PODE REDUZIR A RESERVA DE FERRO E AGRAVAR A ANEMIA. O FÍGADO AFETADO PODE PRODUZIR COAGULOPATIA E SER UM AGRAVANTE.",
    comentarioB12: "A VITAMINA B12 DEVE TER SIDO BENÉFICA. MAS FOI INSUFICIENTE FRENTE À AGRESSÃO MEDULAR, OU ALGO IMPEDIU A SUA ABSORÇÃO, OU A MACROCITOSE NÃO É POR FALTA DELA. SERIA INTERESSANTE O USO DE VITAMINA B12 SUBLINGUAL OU INJETÁVEL. A DOSAGEM NO SANGUE DESSA VITAMINA E DO ÁCIDO FÓLICO É IMPORTANTE NESSE CONTEXTO.",
    comentarioFerro: "O FERRO FOI PROVAVELMENTE DESNECESSÁRIO, MAS SE HAVIA DÉFICIT, FOI CORRIGIDO. MAS SE A FERRITINA ESTÁ ALTA, TAMBÉM PODE TER SIDO NOCIVO. CUIDADO AO REPOR FERRO, ESPECIALMENTE SE PARENTERAL: O EXCESSO É TÓXICO.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","LDH","TSH","FAN","ELETROFORESE DE PROTEÍNAS","ANTI-FATOR INTRÍNSECO","ANTI CÉLULA-PARIETAL","ANTI-H. PYLORI IgG/IgM","HAPTOGLOBINA","COOMBS DIRETO","BILIRRUBINAS","ÁCIDO FÓLICO","AST/ALT","GAMA-GT","CREATININA","ENDOSCOPIA DIGESTIVA","PSA","COLONOSCOPIA"],
  },
  // ─── ID 22 — ALCOOLISMO MUITO GRAVE: ANEMIA MACROCÍTICA IMPORTANTE ───────────
  {
    id: 22,
    label: "ALCOOLISMO MUITO GRAVE — ANEMIA MACROCÍTICA IMPORTANTE",
    color: "red",
    conditions: {
      ferritina:   { min: 24,  max: 1000 },
      hemoglobina: { min: 8.0, max: 12.4 },
      vcm:         { min: 101, max: 120  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 20,  max: 80   },
      bariatrica:  false,
      vegetariano: false,
      perda:       false,
      alcoolista:  true,
      transfundido: false,
    },
    diagnostico: "ANEMIA MACROCÍTICA DESSA MAGNITUDE, NO CONTEXTO DESSA AVALIAÇÃO, SINALIZA CONDIÇÃO MUITO GRAVE, DECORRENTE DE MAIOR IMPACTO TÓXICO E/OU CARENCIAL.\nO ABUSO DE ÁLCOOL É CAUSA FREQUENTE DESSA CONDIÇÃO, MUITAS VEZES AGRAVADO POR MEDICAMENTOS COMO METFORMINA OU INIBIDORES DA BOMBA DE PRÓTONS (PANTOPRAZOL, OMEPRAZOL). OUTROS MEDICAMENTOS COMO HIDROXIUREIA, METOTREXATO, OU UMA GASTRITE AUTOIMUNE PODEM CONTRIBUIR PARA ESSA ANOMALIA, OU SER FATOR DETERMINANTE.\nA CARÊNCIA DE FOLATOS É COMUM NO ALCOOLISMO, AGRAVA A CONDIÇÃO E CONTRIBUI PARA O DESENVOLVIMENTO DE ANEMIA.\nFRASE DATA",
    recomendacaoAge1: "AVALIAÇÃO URGENTE COM HEMATOLOGISTA, QUE PODERÁ SOLICITAR HOSPITALIZAÇÃO PARA EXAMES.\nA DEPENDER DA GRAVIDADE CLÍNICA, PODERÁ SER NECESSÁRIO TRANSFUNDIR.\nSE VOCÊ DOOU SANGUE NO ÚLTIMO ANO, FOI PREJUDICIAL.\nDIFICILMENTE VOCÊ PODERÁ VOLTAR A DOAR SANGUE.",
    recomendacaoAge2: "AVALIAÇÃO URGENTE COM HEMATOLOGISTA.\nESSE GRAU DE ANEMIA NESSA CONDIÇÃO E FAIXA ETÁRIA SUGEREM DOENÇA MUITO GRAVE. A DEPENDER DA GRAVIDADE CLÍNICA, PODERÁ SER NECESSÁRIO TRANSFUNDIR.\nÉ IMPERATIVO SUPLEMENTAR ÁCIDO FÓLICO, VITAMINA B12, PROTEÍNAS, SAIS E OUTRAS VITAMINAS.\nSE VOCÊ DOOU SANGUE NO ÚLTIMO ANO, FOI PREJUDICIAL.\nDIFICILMENTE VOCÊ PODERÁ VOLTAR A DOAR SANGUE.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRÔNICA DE SANGUE EM MUITOS USUÁRIOS. PODE REDUZIR A RESERVA DE FERRO E AGRAVAR A ANEMIA. O FÍGADO AFETADO PODE PRODUZIR COAGULOPATIA E SER UM AGRAVANTE SIGNIFICATIVO.",
    comentarioB12: "A VITAMINA B12 FOI BENÉFICA, MAS INSUFICIENTE PARA MITIGAR A LESÃO MEDULAR, OU ALGO IMPEDIU A SUA ABSORÇÃO, OU A MACROCITOSE NÃO É POR FALTA DELA. SERIA INTERESSANTE O USO DE VITAMINA B12 SUBLINGUAL OU INJETÁVEL. A DOSAGEM NO SANGUE DESSA VITAMINA E DO ÁCIDO FÓLICO É IMPORTANTE NESSE CONTEXTO.",
    comentarioFerro: "O FERRO FOI PROVAVELMENTE DESNECESSÁRIO, MAS SE HAVIA DÉFICIT, FOI CORRIGIDO. MAS SE A FERRITINA ESTÁ ALTA, TAMBÉM PODE TER SIDO NOCIVO. CUIDADO AO REPOR FERRO, ESPECIALMENTE SE PARENTERAL: O EXCESSO É TÓXICO.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","LDH","TSH","FAN","ELETROFORESE DE PROTEÍNAS","BILIRRUBINAS","ANTI-FATOR INTRÍNSECO","ANTI CÉLULA-PARIETAL","ANTI-H. PYLORI IgG/IgM","HAPTOGLOBINA","COOMBS DIRETO","ÁCIDO FÓLICO","ANTI-MITOCÔNDRIA","AST/ALT","GAMA-GT","CREATININA","ENDOSCOPIA DIGESTIVA","PSA","COLONOSCOPIA"],
  },
  // ─── ID 23 — ALCOOLISMO GRAVE COM SOBRECARGA DE FERRO ───────────────────────
  {
    id: 23,
    label: "ALCOOLISMO GRAVE COM SOBRECARGA DE FERRO — ANEMIA MACROCÍTICA SEVERA",
    color: "red",
    conditions: {
      ferritina:   { min: 24,  max: 1500 },
      hemoglobina: { min: 3.0, max: 7.9  },
      vcm:         { min: 101, max: 130  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 50,  max: 100  },
      bariatrica:  false,
      vegetariano: false,
      perda:       false,
      alcoolista:  true,
      transfundido: false,
    },
    diagnostico: "ANEMIA MACROCÍTICA SEVERA NO CONTEXTO DESSA AVALIAÇÃO SINALIZA CONDIÇÃO GRAVÍSSIMA, DECORRENTE DE MÚLTIPLOS FATORES E GRANDE IMPACTO TÓXICO E/OU CARENCIAL.\nO ABUSO DE ÁLCOOL PODE SER O PRINCIPAL FATOR DE GRAVIDADE, MAS COM ESSA INTENSIDADE DA ANEMIA HÁ MÚLTIPLOS FATORES ENVOLVIDOS, MUITAS VEZES AGRAVADO POR IATROGENIA: MEDICAMENTOS COMO METFORMINA OU INIBIDORES DA BOMBA DE PRÓTONS (PANTOPRAZOL, OMEPRAZOL). OUTROS MEDICAMENTOS COMO HIDROXIUREIA, METOTREXATO, OU UMA GASTRITE AUTOIMUNE PODEM CONTRIBUIR E SER AGRAVANTES PODEROSOS.\nA CARÊNCIA DE FOLATOS É COMUM NO ALCOOLISMO, AGRAVA A CONDIÇÃO E CONTRIBUI PARA O DESENVOLVIMENTO DE ANEMIA.\nFRASE DATA",
    recomendacaoAge1: "AVALIAÇÃO URGENTE COM HEMATOLOGISTA, PROVAVELMENTE PARA HOSPITALIZAÇÃO PARA EXAMES E TRATAMENTO.\nPROVAVELMENTE, A CRITÉRIO CLÍNICO, PODERÁ SER NECESSÁRIO TRANSFUNDIR.\nSE VOCÊ DOOU SANGUE NO ÚLTIMO ANO, FOI PREJUDICIAL.\nDIFICILMENTE VOCÊ PODERÁ VOLTAR A DOAR SANGUE.",
    recomendacaoAge2: "AVALIAÇÃO URGENTE COM HEMATOLOGISTA.\nO DESENVOLVIMENTO DE ANEMIA NESSA CONDIÇÃO E FAIXA ETÁRIA SUGEREM DOENÇA GRAVE.\nPROVAVELMENTE, A CRITÉRIO CLÍNICO, PODERÁ SER NECESSÁRIO TRANSFUNDIR.\nTAMBÉM, É IMPERATIVO SUPLEMENTAR ÁCIDO FÓLICO, VITAMINA B12, PROTEÍNAS, SAIS E OUTRAS VITAMINAS.\nSE VOCÊ DOOU SANGUE NO ÚLTIMO ANO, FOI PREJUDICIAL.\nDIFICILMENTE VOCÊ PODERÁ VOLTAR A DOAR SANGUE.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRÔNICA DE SANGUE EM MUITOS USUÁRIOS. PODE REDUZIR A RESERVA DE FERRO E AGRAVAR A ANEMIA. O FÍGADO COM DOENÇA AVANÇADA PRODUZ COAGULOPATIA, UM AGRAVANTE IMPORTANTE.",
    comentarioB12: "A VITAMINA B12 FOI BENÉFICA, MAS INSUFICIENTE PARA MITIGAR A LESÃO MEDULAR OU DETOXICAR ESSE QUADRO GRAVE, OU ALGO IMPEDIU A SUA ABSORÇÃO, OU A MACROCITOSE É MULTIFATORIAL. SERIA INTERESSANTE O USO DE VITAMINA B12 SUBLINGUAL OU INJETÁVEL. A DOSAGEM NO SANGUE DESSA VITAMINA E DO ÁCIDO FÓLICO É IMPORTANTE NESSE CONTEXTO.",
    comentarioFerro: "O FERRO FOI PROVAVELMENTE DESNECESSÁRIO, MAS SE HAVIA DÉFICIT, FOI CORRIGIDO. MAS SE A FERRITINA E A SATURAÇÃO DA TRANSFERRINA ESTÃO ALTAS, DEVE TER SIDO MUITO NOCIVO. CUIDADO AO REPOR FERRO, ESPECIALMENTE SE PARENTERAL: O EXCESSO É TÓXICO.",
    proximosExames: ["HEMOGRAMA","RETICULÓCITOS","FERRITINA","SATURAÇÃO DA TRANSFERRINA","VITAMINA B12","LDH","TSH","FAN","ELETROFORESE DE PROTEÍNAS","BILIRRUBINAS","ANTI-FATOR INTRÍNSECO","ANTI CÉLULA-PARIETAL","ANTI-H. PYLORI IgG/IgM","HAPTOGLOBINA","COOMBS DIRETO","ÁCIDO FÓLICO","ANTI-MITOCÔNDRIA","AST/ALT","GAMA-GT","CREATININA","ENDOSCOPIA DIGESTIVA","PSA","COLONOSCOPIA"],
  },
'@

# Função para inserir antes do fechamento ];
function Add-Entries($file, $entries, $label) {
    $content = Get-Content $file -Raw -Encoding UTF8
    if ($content -match 'id: 20,') {
        Write-Host "  ℹ️  $label`: IDs 20-23 já presentes"
        return
    }
    # Inserir antes do fechamento ];
    $content = $content -replace '(\n\];?\s*)$', "$entries`n];"
    Set-Content $file $content -NoNewline -Encoding UTF8
    Write-Host "  ✅ $label`: IDs 20, 21, 22, 23 adicionados"
}

Write-Host "`n🔧 Adicionando IDs de alcoolismo..."
Add-Entries $fem $novasEntradas "femaleMatrix"
Add-Entries $mal $novasEntradas "maleMatrix"

Write-Host "`n=== PRONTO ==="
Write-Host "Agora rode:"
Write-Host "  git add . && git commit -m `"feat: IDs alcoolismo 20-23 nas matrizes`" && git push origin main"
