# -*- coding: utf-8 -*-
# RedFairy — Adicionar IDs de Alcoolismo (20, 21, 22, 23)
# Execute em: C:\Users\Estacio\Desktop\redfairy\src\engine
# python add_alcoolismo.py

import os, re

dir_ = os.path.dirname(os.path.abspath(__file__))
fem  = os.path.join(dir_, 'femaleMatrix.js')
mal  = os.path.join(dir_, 'maleMatrix.js')

NOVAS = """
  // ─── ID 20 — ALCOOLISMO: MACROCITOSE SEM ANEMIA ─────────────────────────────
  {
    id: 20,
    label: "ALCOOLISMO — MACROCITOSE SEM ANEMIA",
    color: "yellow",
    conditions: {
      ferritina:   { min: 24,  max: 400  },
      hemoglobina: { min: 13.5,max: 17.5 },
      vcm:         { min: 101, max: 115  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 20,  max: 80   },
      bariatrica:  false,
      vegetariano: false,
      perda:       false,
      alcoolista:  true,
      transfundido: false,
    },
    diagnostico: "A PRESENCA DE CELULAS VERMELHAS MAIORES PODE OCORRER ANTES DO ESTABELECIMENTO DE ANEMIA, COMO SE VE NESSA AVALIACAO.\\nO ABUSO DE ALCOOL E CAUSA FREQUENTE DESSA CONDICAO, MAS MEDICAMENTOS COMO METFORMINA OU INIBIDORES DA BOMBA DE PROTONS (PANTOPRAZOL, OMEPRAZOL), HIDROXIUREIA, METOTREXATO, OU UMA GASTRITE AUTOIMUNE PODEM CONTRIBUIR PARA ESSA ANOMALIA, OU SER FATOR DETERMINANTE.\\nA CARENCIA DE FOLATOS E COMUM NO ALCOOLISMO, AGRAVA A CONDICAO E CONTRIBUI PARA O DESENVOLVIMENTO DE ANEMIA.\\nFRASE DATA",
    recomendacaoAge1: "AVALIACAO COM HEMATOLOGISTA.\\nINICIE ACIDO FOLICO, 5 mg VIA ORAL POR DIA.\\nSE VOCE DOOU SANGUE NOS ULTIMOS MESES, PODE TER SIDO PREJUDICIAL.\\nVOCE PRECISARA SER AVALIADO POR MEDICO ANTES DE DOAR SANGUE.",
    recomendacaoAge2: "AVALIACAO COM HEMATOLOGISTA.\\nESSA CONDICAO, NESSA FAIXA ETARIA IMPOE GARANTIR A SUPLEMENTACAO DE ACIDO FOLICO, VITAMINA B12, PROTEINAS, SAIS E OUTRAS VITAMINAS.\\nSE VOCE DOOU SANGUE NOS ULTIMOS MESES, PODE TER SIDO PREJUDICIAL.\\nVOCE PRECISARA SER AVALIADO POR MEDICO ANTES DE DOAR SANGUE.",
    comentarioAspirina: "ASPIRINA IMPOE PEQUENA PERDA CRONICA DE SANGUE A MAIORIA DOS USUARIOS, MAS AQUI NAO SE OBSERVA IMPACTO NEGATIVO.",
    comentarioB12: "A VITAMINA B12 NAO ERA NECESSARIA, MAS DEVE TER SIDO BENEFICA. MAS FOI INSUFICIENTE, OU ALGO IMPEDIU A SUA ABSORCAO, OU A MACROCITOSE NAO E POR FALTA DELA. SERIA INTERESSANTE O USO DE VITAMINA B12 SUBLINGUAL OU INJETAVEL. A DOSAGEM NO SANGUE DESSA VITAMINA E DO ACIDO FOLICO E IMPORTANTE NESSE CONTEXTO.",
    comentarioFerro: "O FERRO FOI PROVAVELMENTE DESNECESSARIO, MAS SE HAVIA DEFICIT, FOI CORRIGIDO. MAS SE A FERRITINA ESTA ALTA, TAMBEM PODE TER SIDO NOCIVO. CUIDADO AO REPOR FERRO, ESPECIALMENTE SE PARENTERAL: O EXCESSO E TOXICO.",
    proximosExames: ["HEMOGRAMA","FERRITINA","SATURACAO DA TRANSFERRINA","VITAMINA B12","ACIDO FOLICO","AST/ALT","LDH","TSH","GAMA-GT","ELETROFORESE DE PROTEINAS","HAPTOGLOBINA","ANTI-H. PYLORI IgG/IgM","PSA","COLONOSCOPIA DE ROTINA"],
  },
  // ─── ID 21 — ALCOOLISMO GRAVE: ANEMIA MACROCÍTICA MODERADA ──────────────────
  {
    id: 21,
    label: "ALCOOLISMO GRAVE — ANEMIA MACROCÍTICA MODERADA",
    color: "orange",
    conditions: {
      ferritina:   { min: 24,  max: 600  },
      hemoglobina: { min: 12.5,max: 13.4 },
      vcm:         { min: 101, max: 120  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 20,  max: 80   },
      bariatrica:  false,
      vegetariano: false,
      perda:       false,
      alcoolista:  true,
      transfundido: false,
    },
    diagnostico: "A PRESENCA DE CELULAS VERMELHAS MAIORES COM ANEMIA, NO CONTEXTO DESSA AVALIACAO, SINALIZA CONDICAO MAIS GRAVE, MAIOR IMPACTO TOXICO E/OU CARENCIAL.\\nO ABUSO DE ALCOOL E CAUSA FREQUENTE DESSA CONDICAO, MUITAS VEZES AGRAVADO POR MEDICAMENTOS COMO METFORMINA OU INIBIDORES DA BOMBA DE PROTONS (PANTOPRAZOL, OMEPRAZOL). OUTROS MEDICAMENTOS COMO HIDROXIUREIA, METOTREXATO, OU UMA GASTRITE AUTOIMUNE PODEM CONTRIBUIR PARA ESSA ANOMALIA, OU SER FATOR DETERMINANTE.\\nA CARENCIA DE FOLATOS E COMUM NO ALCOOLISMO, AGRAVA A CONDICAO E CONTRIBUI PARA O DESENVOLVIMENTO DE ANEMIA.\\nFRASE DATA",
    recomendacaoAge1: "AVALIACAO COM HEMATOLOGISTA ASSIM QUE POSSIVEL.\\nSE VOCE DOOU SANGUE NOS ULTIMOS MESES, PODE TER SIDO PREJUDICIAL.\\nVOCE PRECISARA SER AVALIADO POR MEDICO ANTES DE DOAR SANGUE.\\nSOMENTE SE RECUPERADO VOCE PODERA DOAR SANGUE.",
    recomendacaoAge2: "AVALIACAO COM HEMATOLOGISTA ASSIM QUE POSSIVEL.\\nO DESENVOLVIMENTO DE ANEMIA NESSA CONDICAO E FAIXA ETARIA SUGEREM DOENCA MAIS IMPORTANTE.\\nE IMPERATIVO SUPLEMENTAR ACIDO FOLICO, VITAMINA B12, PROTEINAS, SAIS E OUTRAS VITAMINAS.\\nSE VOCE DOOU SANGUE NOS ULTIMOS MESES, PODE TER SIDO PREJUDICIAL.\\nVOCE PRECISARA SER AVALIADO POR MEDICO ANTES DE DOAR SANGUE.\\nSOMENTE SE RECUPERADO VOCE PODERA DOAR SANGUE.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRONICA DE SANGUE EM MUITOS USUARIOS. PODE REDUZIR A RESERVA DE FERRO E AGRAVAR A ANEMIA. O FIGADO AFETADO PODE PRODUZIR COAGULOPATIA E SER UM AGRAVANTE.",
    comentarioB12: "A VITAMINA B12 DEVE TER SIDO BENEFICA. MAS FOI INSUFICIENTE FRENTE A AGRESSAO MEDULAR, OU ALGO IMPEDIU A SUA ABSORCAO, OU A MACROCITOSE NAO E POR FALTA DELA. SERIA INTERESSANTE O USO DE VITAMINA B12 SUBLINGUAL OU INJETAVEL. A DOSAGEM NO SANGUE DESSA VITAMINA E DO ACIDO FOLICO E IMPORTANTE NESSE CONTEXTO.",
    comentarioFerro: "O FERRO FOI PROVAVELMENTE DESNECESSARIO, MAS SE HAVIA DEFICIT, FOI CORRIGIDO. MAS SE A FERRITINA ESTA ALTA, TAMBEM PODE TER SIDO NOCIVO. CUIDADO AO REPOR FERRO, ESPECIALMENTE SE PARENTERAL: O EXCESSO E TOXICO.",
    proximosExames: ["HEMOGRAMA","RETICULOCITOS","FERRITINA","SATURACAO DA TRANSFERRINA","VITAMINA B12","LDH","TSH","FAN","ELETROFORESE DE PROTEINAS","ANTI-FATOR INTRINSECO","ANTI CELULA-PARIETAL","ANTI-H. PYLORI IgG/IgM","HAPTOGLOBINA","COOMBS DIRETO","BILIRRUBINAS","ACIDO FOLICO","AST/ALT","GAMA-GT","CREATININA","ENDOSCOPIA DIGESTIVA","PSA","COLONOSCOPIA"],
  },
  // ─── ID 22 — ALCOOLISMO MUITO GRAVE: ANEMIA MACROCÍTICA IMPORTANTE ───────────
  {
    id: 22,
    label: "ALCOOLISMO MUITO GRAVE — ANEMIA MACROCÍTICA IMPORTANTE",
    color: "red",
    conditions: {
      ferritina:   { min: 24,  max: 1000 },
      hemoglobina: { min: 8.0, max: 12.4 },
      vcm:         { min: 101, max: 120  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 20,  max: 80   },
      bariatrica:  false,
      vegetariano: false,
      perda:       false,
      alcoolista:  true,
      transfundido: false,
    },
    diagnostico: "ANEMIA MACROCÍTICA DESSA MAGNITUDE, NO CONTEXTO DESSA AVALIACAO, SINALIZA CONDICAO MUITO GRAVE, DECORRENTE DE MAIOR IMPACTO TOXICO E/OU CARENCIAL.\\nO ABUSO DE ALCOOL E CAUSA FREQUENTE DESSA CONDICAO, MUITAS VEZES AGRAVADO POR MEDICAMENTOS COMO METFORMINA OU INIBIDORES DA BOMBA DE PROTONS (PANTOPRAZOL, OMEPRAZOL). OUTROS MEDICAMENTOS COMO HIDROXIUREIA, METOTREXATO, OU UMA GASTRITE AUTOIMUNE PODEM CONTRIBUIR PARA ESSA ANOMALIA, OU SER FATOR DETERMINANTE.\\nA CARENCIA DE FOLATOS E COMUM NO ALCOOLISMO, AGRAVA A CONDICAO E CONTRIBUI PARA O DESENVOLVIMENTO DE ANEMIA.\\nFRASE DATA",
    recomendacaoAge1: "AVALIACAO URGENTE COM HEMATOLOGISTA, QUE PODERA SOLICITAR HOSPITALIZACAO PARA EXAMES.\\nA DEPENDER DA GRAVIDADE CLINICA, PODERA SER NECESSARIO TRANSFUNDIR.\\nSE VOCE DOOU SANGUE NO ULTIMO ANO, FOI PREJUDICIAL.\\nDIFICILMENTE VOCE PODERA VOLTAR A DOAR SANGUE.",
    recomendacaoAge2: "AVALIACAO URGENTE COM HEMATOLOGISTA.\\nESSE GRAU DE ANEMIA NESSA CONDICAO E FAIXA ETARIA SUGEREM DOENCA MUITO GRAVE. A DEPENDER DA GRAVIDADE CLINICA, PODERA SER NECESSARIO TRANSFUNDIR.\\nE IMPERATIVO SUPLEMENTAR ACIDO FOLICO, VITAMINA B12, PROTEINAS, SAIS E OUTRAS VITAMINAS.\\nSE VOCE DOOU SANGUE NO ULTIMO ANO, FOI PREJUDICIAL.\\nDIFICILMENTE VOCE PODERA VOLTAR A DOAR SANGUE.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRONICA DE SANGUE EM MUITOS USUARIOS. PODE REDUZIR A RESERVA DE FERRO E AGRAVAR A ANEMIA. O FIGADO AFETADO PODE PRODUZIR COAGULOPATIA E SER UM AGRAVANTE SIGNIFICATIVO.",
    comentarioB12: "A VITAMINA B12 FOI BENEFICA, MAS INSUFICIENTE PARA MITIGAR A LESAO MEDULAR, OU ALGO IMPEDIU A SUA ABSORCAO, OU A MACROCITOSE NAO E POR FALTA DELA. SERIA INTERESSANTE O USO DE VITAMINA B12 SUBLINGUAL OU INJETAVEL. A DOSAGEM NO SANGUE DESSA VITAMINA E DO ACIDO FOLICO E IMPORTANTE NESSE CONTEXTO.",
    comentarioFerro: "O FERRO FOI PROVAVELMENTE DESNECESSARIO, MAS SE HAVIA DEFICIT, FOI CORRIGIDO. MAS SE A FERRITINA ESTA ALTA, TAMBEM PODE TER SIDO NOCIVO. CUIDADO AO REPOR FERRO, ESPECIALMENTE SE PARENTERAL: O EXCESSO E TOXICO.",
    proximosExames: ["HEMOGRAMA","RETICULOCITOS","FERRITINA","SATURACAO DA TRANSFERRINA","VITAMINA B12","LDH","TSH","FAN","ELETROFORESE DE PROTEINAS","BILIRRUBINAS","ANTI-FATOR INTRINSECO","ANTI CELULA-PARIETAL","ANTI-H. PYLORI IgG/IgM","HAPTOGLOBINA","COOMBS DIRETO","ACIDO FOLICO","ANTI-MITOCONDRIA","AST/ALT","GAMA-GT","CREATININA","ENDOSCOPIA DIGESTIVA","PSA","COLONOSCOPIA"],
  },
  // ─── ID 23 — ALCOOLISMO GRAVE COM SOBRECARGA DE FERRO ───────────────────────
  {
    id: 23,
    label: "ALCOOLISMO GRAVE COM SOBRECARGA DE FERRO — ANEMIA MACROCÍTICA SEVERA",
    color: "red",
    conditions: {
      ferritina:   { min: 24,  max: 1500 },
      hemoglobina: { min: 3.0, max: 7.9  },
      vcm:         { min: 101, max: 130  },
      rdw:         { min: 15.1,max: 999  },
      satTransf:   { min: 50,  max: 100  },
      bariatrica:  false,
      vegetariano: false,
      perda:       false,
      alcoolista:  true,
      transfundido: false,
    },
    diagnostico: "ANEMIA MACROCÍTICA SEVERA NO CONTEXTO DESSA AVALIACAO SINALIZA CONDICAO GRAVISSIMA, DECORRENTE DE MULTIPLOS FATORES E GRANDE IMPACTO TOXICO E/OU CARENCIAL.\\nO ABUSO DE ALCOOL PODE SER O PRINCIPAL FATOR DE GRAVIDADE, MAS COM ESSA INTENSIDADE DA ANEMIA HA MULTIPLOS FATORES ENVOLVIDOS, MUITAS VEZES AGRAVADO POR IATROGENIA: MEDICAMENTOS COMO METFORMINA OU INIBIDORES DA BOMBA DE PROTONS (PANTOPRAZOL, OMEPRAZOL). OUTROS MEDICAMENTOS COMO HIDROXIUREIA, METOTREXATO, OU UMA GASTRITE AUTOIMUNE PODEM CONTRIBUIR E SER AGRAVANTES PODEROSOS.\\nA CARENCIA DE FOLATOS E COMUM NO ALCOOLISMO, AGRAVA A CONDICAO E CONTRIBUI PARA O DESENVOLVIMENTO DE ANEMIA.\\nFRASE DATA",
    recomendacaoAge1: "AVALIACAO URGENTE COM HEMATOLOGISTA, PROVAVELMENTE PARA HOSPITALIZACAO PARA EXAMES E TRATAMENTO.\\nPROVAVELMENTE, A CRITERIO CLINICO, PODERA SER NECESSARIO TRANSFUNDIR.\\nSE VOCE DOOU SANGUE NO ULTIMO ANO, FOI PREJUDICIAL.\\nDIFICILMENTE VOCE PODERA VOLTAR A DOAR SANGUE.",
    recomendacaoAge2: "AVALIACAO URGENTE COM HEMATOLOGISTA.\\nO DESENVOLVIMENTO DE ANEMIA NESSA CONDICAO E FAIXA ETARIA SUGEREM DOENCA GRAVE.\\nPROVAVELMENTE, A CRITERIO CLINICO, PODERA SER NECESSARIO TRANSFUNDIR.\\nTAMBEM, E IMPERATIVO SUPLEMENTAR ACIDO FOLICO, VITAMINA B12, PROTEINAS, SAIS E OUTRAS VITAMINAS.\\nSE VOCE DOOU SANGUE NO ULTIMO ANO, FOI PREJUDICIAL.\\nDIFICILMENTE VOCE PODERA VOLTAR A DOAR SANGUE.",
    comentarioAspirina: "ASPIRINA PRODUZ PEQUENA PERDA CRONICA DE SANGUE EM MUITOS USUARIOS. PODE REDUZIR A RESERVA DE FERRO E AGRAVAR A ANEMIA. O FIGADO COM DOENCA AVANCADA PRODUZ COAGULOPATIA, UM AGRAVANTE IMPORTANTE.",
    comentarioB12: "A VITAMINA B12 FOI BENEFICA, MAS INSUFICIENTE PARA MITIGAR A LESAO MEDULAR OU DETOXICAR ESSE QUADRO GRAVE, OU ALGO IMPEDIU A SUA ABSORCAO, OU A MACROCITOSE E MULTIFATORIAL. SERIA INTERESSANTE O USO DE VITAMINA B12 SUBLINGUAL OU INJETAVEL. A DOSAGEM NO SANGUE DESSA VITAMINA E DO ACIDO FOLICO E IMPORTANTE NESSE CONTEXTO.",
    comentarioFerro: "O FERRO FOI PROVAVELMENTE DESNECESSARIO, MAS SE HAVIA DEFICIT, FOI CORRIGIDO. MAS SE A FERRITINA E A SATURACAO DA TRANSFERRINA ESTAO ALTAS, DEVE TER SIDO MUITO NOCIVO. CUIDADO AO REPOR FERRO, ESPECIALMENTE SE PARENTERAL: O EXCESSO E TOXICO.",
    proximosExames: ["HEMOGRAMA","RETICULOCITOS","FERRITINA","SATURACAO DA TRANSFERRINA","VITAMINA B12","LDH","TSH","FAN","ELETROFORESE DE PROTEINAS","BILIRRUBINAS","ANTI-FATOR INTRINSECO","ANTI CELULA-PARIETAL","ANTI-H. PYLORI IgG/IgM","HAPTOGLOBINA","COOMBS DIRETO","ACIDO FOLICO","ANTI-MITOCONDRIA","AST/ALT","GAMA-GT","CREATININA","ENDOSCOPIA DIGESTIVA","PSA","COLONOSCOPIA"],
  },
"""

def add_entries(path, label):
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    if 'id: 20,' in content:
        print(f"  INFO {label}: IDs 20-23 já presentes")
        return
    # Inserir antes do fechamento ];
    content = content.rstrip()
    if content.endswith('];'):
        content = content[:-2] + NOVAS + '\n];\n'
    elif content.endswith(']'):
        content = content[:-1] + NOVAS + '\n];\n'
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  OK {label}: IDs 20, 21, 22, 23 adicionados")

print("\nAdicionando IDs de alcoolismo...")
add_entries(fem, 'femaleMatrix')
add_entries(mal, 'maleMatrix')
print("\n=== PRONTO ===")
print("Agora rode:")
print('  git add . && git commit -m "feat: IDs alcoolismo 20-23 nas matrizes" && git push origin main')
